/*
 * JSP generated by Resin Professional 3.0.17 (built Tue, 19 Sep 2006 05:00:05 PDT)
 */

package _jsp._chapter7._bootcloset;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _getTerm__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.pageSetOrRemove("term", _caucho_expr_0.evalObject(pageContext));
      out.write('\n');
      if (_caucho_expr_1.evalBoolean(pageContext)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
      }
      else if (_caucho_expr_2.evalBoolean(pageContext)) {
        out.write(_jsp_string2, 0, _jsp_string2.length);
      }
      else if (_caucho_expr_3.evalBoolean(pageContext)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
      }
      else if (_caucho_expr_4.evalBoolean(pageContext)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      else if (_caucho_expr_5.evalBoolean(pageContext)) {
        out.write(_jsp_string5, 0, _jsp_string5.length);
      }
      else if (_caucho_expr_6.evalBoolean(pageContext)) {
        out.write(_jsp_string6, 0, _jsp_string6.length);
      }
      else if (_caucho_expr_7.evalBoolean(pageContext)) {
        out.write(_jsp_string7, 0, _jsp_string7.length);
      }
      else if (_caucho_expr_8.evalBoolean(pageContext)) {
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      else {
        out.write(_jsp_string9, 0, _jsp_string9.length);
      }
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 4553760446147460671L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("chapter7/bootcloset/getTerm.jsp"), -1494773449005156148L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("prelude.jspf"), -8866566771637529728L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.FunctionExpr(new com.caucho.el.StaticMethodExpr("java.lang.String org.apache.taglibs.standard.functions.Functions.toLowerCase(java.lang.String)"), new com.caucho.el.Expr[] {new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("term"))})
;
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("oil-tanned"));
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("full-grain"));
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("vibram"));
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("goodyear welt"));
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("cambrelle"));
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("cordura"));
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("gore-tex"));
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.EqExpr(6, new com.caucho.el.IdExpr("term"), new com.caucho.el.StringLiteral("stitch-down"));

  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string6;
  private final static char []_jsp_string9;
  private final static char []_jsp_string5;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  static {
    _jsp_string7 = "\n    A water-proof and breathable fabric that offers superior insulating abilities in a light-weight fabric.\n  ".toCharArray();
    _jsp_string2 = "\n    Leather which has not been altered beyond hair removal. Full grain leather is the most genuine type of leather, as it retains all of the original texture and markings of the original hide.\n  ".toCharArray();
    _jsp_string3 = "\n    A brand of boot and shoe sole created by Vitale Bramani in the 1930's, orginally for climbing boots. The Vibram&reg; brand is recognized worldwide as the leader in high performance soling products for outdoor, dress casual, and service footwear.\n  ".toCharArray();
    _jsp_string1 = "\n    A method of leather tanning in where oils or fats are used to cure the leather. Such leather usually has a matte or \"oily\" finish ans is not generally polishable.\n  ".toCharArray();
    _jsp_string6 = "\n    A certified fabric from INVISTA used in a wide range of products from luggage and backpacks to boots, to military wear and performance apparel. Cordura\u00a8 is resistant to abrasions, tears and scuffs.\n  ".toCharArray();
    _jsp_string9 = "\n    Unknown term.\n  ".toCharArray();
    _jsp_string5 = "\n     A non-woven synthetic fabric used primarily as a lining for shoes, boots and slippers.\n  ".toCharArray();
    _jsp_string8 = "\n    A method of boot construction that helps seal the boot against dirt, mud and water and maximizes flexibility.\n  ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string4 = "\n    The Goodyear welt is a method of attaching the sole of a shoe to the upper that is  hand-stitched and allows multiple sole replacements, extending the life of the footwear.\n  ".toCharArray();
  }
}
