/*
 * JSP generated by Resin Professional 3.0.17 (built Tue, 19 Sep 2006 05:00:05 PDT)
 */

package _jsp._chapter7._bootcloset;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _getDetailsWithTerms__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      com.caucho.el.Expr.setProperty(_caucho_expr_0.evalObject(pageContext), "contentType", "text/json");
      out.write('\n');
      if (_caucho_expr_1.evalBoolean(pageContext)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
      }
      else if (_caucho_expr_2.evalBoolean(pageContext)) {
        out.write(_jsp_string2, 0, _jsp_string2.length);
      }
      else if (_caucho_expr_3.evalBoolean(pageContext)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
      }
      else if (_caucho_expr_4.evalBoolean(pageContext)) {
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      else if (_caucho_expr_5.evalBoolean(pageContext)) {
        out.write(_jsp_string5, 0, _jsp_string5.length);
      }
      else if (_caucho_expr_6.evalBoolean(pageContext)) {
        out.write(_jsp_string6, 0, _jsp_string6.length);
      }
      else if (_caucho_expr_7.evalBoolean(pageContext)) {
        out.write(_jsp_string7, 0, _jsp_string7.length);
      }
      else if (_caucho_expr_8.evalBoolean(pageContext)) {
        out.write(_jsp_string8, 0, _jsp_string8.length);
      }
      else {
        out.write(_jsp_string9, 0, _jsp_string9.length);
      }
      out.write('\n');
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 4553760446147460671L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("chapter7/bootcloset/getDetailsWithTerms.jsp"), 4052513907577514679L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("prelude.jspf"), -8866566771637529728L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.ArrayExpr(new com.caucho.jsp.el.ImplicitObjectExpr("pageContext"), new com.caucho.el.StringLiteral("response"));
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7141832"));
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7173656"));
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7141922"));
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7177382"));
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7141730"));
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7141833"));
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7257914"));
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.EqExpr(6, new com.caucho.jsp.el.ImplicitFieldExpr(6, new com.caucho.el.StringLiteral("style")), new com.caucho.el.StringLiteral("7269643"));

  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  static {
    _jsp_string9 = "\n    {\n      name: '---',\n      sku: '---',\n      height: '---',\n      lining: '---',\n      colors: '---',\n      price: '---'\n    }\n  ".toCharArray();
    _jsp_string1 = "\n    {\n      name: 'Chippewa 17\" Engineer Boot',\n      sku: '7141832',\n      height: '17\"',\n      lining: 'leather',\n      colors: 'Black <abbr>Oil-tanned</abbr>, Black Polishable',\n      price: '$187.00',\n      features: '<abbr>Oil-tanned</abbr> or polishable <abbr>full-grain</abbr> leather uppers. <abbr>Vibram</abbr> sole. <abbr>Goodyear welt</abbr>. Padded insole. Steel safety toe.'\n    }\n  ".toCharArray();
    _jsp_string5 = "\n    {\n      name: 'Danner Foreman Pro Work Boot',\n      sku: '7141730',\n      height: '10\"',\n      lining: 'leather',\n      colors: 'Honey, Brown',\n      price: '$287.00',\n      features: 'Alkali-resistant <abbr>full-grain</abbr> leather. <abbr>Cambrelle</abbr> nylon lining. Fiberglass shank. <abbr>Vibram</abbr> 4014 Cristy sole. <abbr>Stitch-down</abbr> construction.'\n    }\n  ".toCharArray();
    _jsp_string3 = "\n    {\n      name: 'Chippewa Harness Boot',\n      sku: '7141922',\n      height: '13\"',\n      lining: 'leather',\n      colors: 'Black, Crazy Horse',\n      price: '$187.00',\n      features: '<abbr>Full-grain</abbr> leather uppers. Leather lining. <abbr>Vibram</abbr> sole. <abbr>Goodyear welt</abbr>.'\n    }\n  ".toCharArray();
    _jsp_string4 = "\n    {\n      name: 'Caterpillar Tradesman Work Boot',\n      sku: '7177382',\n      height: '6\"',\n      lining: 'leather',\n      colors: 'Honey, Peanut',\n      price: '$87.00',\n      features: '<abbr>Full-grain</abbr> <abbr>Oil-tanned</abbr> leather, Nylon mesh lining. Ortholite sock liner. EVA midsole. T84V Rubberlon outsole.'\n    }\n  ".toCharArray();
    _jsp_string6 = "\n    {\n      name: 'Chippewa 17\" Snakeproof Boot',\n      sku: '7141833',\n      height: '17\"',\n      lining: 'leather',\n      colors: 'Russet',\n      price: '$147.00',\n      features: '<abbr>Full-grain</abbr> leather foot. 1000 Denier <abbr>Cordura</abbr> Viper cloth shaft. <abbr>Goodyear welt</abbr>. Leather Lining. Body Cushion Insole. <abbr>Vibram</abbr> Robinson Outsole.'\n    }\n  ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n".toCharArray();
    _jsp_string7 = "\n    {\n      name: 'Danner Grouse GTX Boot',\n      sku: '7257914',\n      height: '8\"',\n      lining: '<abbr>Gore-Tex</abbr>',\n      colors: 'Brown',\n      price: '$207.00',\n      features: '<abbr>Full-grain</abbr> leather foot. 1000 Denier <abbr>Cordura</abbr> Viper cloth shaft. <abbr>Gore-Tex</abbr> lining. <abbr>Stitch-down</abbr> construction.'\n    }\n  ".toCharArray();
    _jsp_string2 = "\n    {\n      name: 'Chippewa 11\" Engineer Boot',\n      sku: '7173656',\n      height: '11\"',\n      lining: 'none',\n      colors: 'Black, Crazy Horse',\n      price: '$167.00',\n      features: '<abbr>Oil-tanned</abbr> <abbr>full-grain</abbr> leather uppers. <abbr>Vibram</abbr> sole. <abbr>Goodyear welt</abbr>. Padded insole. Steel safety toe. Texon&reg; insole.'\n    }\n  ".toCharArray();
    _jsp_string8 = "\n    {\n      name: 'Caterpillar Logger Boot',\n      sku: '7269643',\n      height: '8\"',\n      lining: '<abbr>Cambrelle</abbr>',\n      colors: 'Black',\n      price: '$157.00',\n      features: '<abbr>Full-grain</abbr> leather. <abbr>Cambrelle</abbr>&reg; lining. Steel safety toe. Electrical hazard protection. Poliyou&reg; cushion insole. Rubber lug outsole.'\n    }\n  ".toCharArray();
  }
}
